moved ./lib to ./bin/lib to keep the relative position of the libraries to executables consistent across the project

diff --git a/src/main/bash/bin/em b/src/main/bash/bin/em
--- a/src/main/bash/bin/em
+++ b/src/main/bash/bin/em
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-lib=$(dirname $0)/../lib/std.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
-lib=$(dirname $0)/../lib/em.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
+lib=$(dirname $0)/lib/std.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
+lib=$(dirname $0)/lib/em.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
 
 export version=2.5
 export release_date="05/06/15"
