'burn' work

diff --git a/src/main/bash/bin/em b/src/main/bash/bin/em
--- a/src/main/bash/bin/em
+++ b/src/main/bash/bin/em
@@ -3,16 +3,19 @@
 # the entry point in em. This script should be placed in PATH
 #
 
-[ -f $(dirname $0)/../em.shlib ] && . $(dirname $0)/../em.shlib || { echo "$(dirname $0)/../em.shlib not found" 1>&2; exit 1; }
+[ -f $(dirname $0)/../lib/em.shlib ] && . $(dirname $0)/../lib/em.shlib || { echo "$(dirname $0)/../lib/em.shlib not found" 1>&2; exit 1; }
 
 function main
 {
     local command
     local command_args
+    local dry_run=false
 
     while [ "$1" != "" ]; do
         if [ "$1" = "--debug" ]; then
             debug_off=false
+        elif [ "$1" = "--dry-run" ]; then
+            dry_run=true
         elif [ "${command}" = "" ]; then
             command=$1
         else
@@ -25,6 +28,10 @@ function main
 
     [ ! -f $(dirname $0)/../commands/${command} ] && { echo "no such command '${command}'"; exit 1; }
 
+    ! ${debug_off} && debug_arg="--debug"
+    ${dry_run} && dry_run_arg="--dry-run"
+
+    $(dirname $0)/../commands/${command} ${debug_arg} ${dry_run_arg} ${command_args}
 
 }
 
diff --git a/src/main/bash/commands/burn b/src/main/bash/commands/burn
--- a/src/main/bash/commands/burn
+++ b/src/main/bash/commands/burn
@@ -1,2 +1,54 @@
 #!/bin/bash
 
+[ -f $(dirname $0)/../lib/em.shlib ] && . $(dirname $0)/../lib/em.shlib || { echo "$(dirname $0)/../lib/em.shlib not found" 1>&2; exit 1; }
+
+function main
+{
+    local id
+    local debug_arg
+    local dry_run_arg
+
+    while [ "$1" != "" ]; do
+        if [ "$1" = "--debug" ]; then
+            debug_arg=$1
+            debug_off=false
+        elif [ "$1" = "--dry-run" ]; then
+            dry_run_arg=$1
+        elif [ "${id}" = "" ]; then
+            id=$1
+        fi
+        shift
+    done
+
+    # copy the installation key in a temporary location and give it the right ownership and persmissions
+
+    local temp_installation_key=/tmp/.tmpk
+
+    cp $(dirname $0)/../../resources/installation_access.pem ${temp_installation_key} || \
+        { echo "failed to copy installation key into /tmp" 1>&2; exit 1; }
+
+    sudo chown ec2-user:ec2-user ${temp_installation_key} || \
+        { echo "failed to chown ec2-user:ec2-user installation key" 1>&2; exit 1; }
+
+    chmod go-rwx ${temp_installation_key} \
+        || { echo "failed to chmod go-rwx installation key" 1>&2; exit 1; }
+
+#    local target_ip
+#    target_ip=$(id-to-ip ${id}) || exit 1
+    target_ip=172.31.16.203
+
+    # copy the library on the host we're going to burn in
+    scp -q -i ${temp_installation_key} $(dirname $0)/../lib/em.shlib ec2-user@${target_ip}:/tmp
+
+    # copy the driving script
+    scp -q -i ${temp_installation_key} $(dirname $0)/../remote-scripts/* ec2-user@${target_ip}:/tmp
+
+    # run the driving script
+    ssh -q -t -i ${temp_installation_key} ec2-user@${target_ip} \
+        "chmod u+x /tmp/local-burn; sudo /tmp/local-burn ${debug_arg} ${dry_run_arg} ${id}"
+
+    # delete the isntallation key
+    rm ${temp_installation_key} || { echo "failed to remove installation key" 1>&2; exit 1; }
+}
+
+main $@
