added the 'amq-broker' overlay. Step 2 and final

diff --git a/src/main/bash/bin/commands/overlay b/src/main/bash/bin/commands/overlay
--- a/src/main/bash/bin/commands/overlay
+++ b/src/main/bash/bin/commands/overlay
@@ -71,17 +71,31 @@ function main()
     # tar gz the em bits that are needed remote; we don't use zip because zip/unzip might not be installed yet
     #
 
-    local gzip_file=$(unique-file).tar.gz
-    local tar_root=$(dirname $0)/../..
     local gzip_quiet="-q"
     local tar_verbose=""
     ${verbose} && { gzip_quiet=""; tar_verbose="v"; }
 
+    local tar_file=$(unique-file).tar
+    local gzip_file=${tar_file}.gz
+    local tar_root=$(dirname $0)/../..
+
+    debug "tar_file: ${tar_file}"
+    debug "gzip_file: ${gzip_file}"
     debug "tar_root: ${tar_root}"
 
-    (cd ${tar_root}; tar cf${tar_verbose} - bin/overlays bin/lib etc | gzip ${gzip_quiet} > ${gzip_file}) || fail "failed to create ${gzip_file}"
+    (cd ${tar_root}; tar cf${tar_verbose} - bin/overlays bin/lib etc > ${tar_file}) || fail "failed to create ${tar_file}"
 
-    debug "gzip file ${gzip_file} created"
+    tar_root=$(dirname $0)/../../../../../target
+    debug "tar_root: ${tar_root}"
+
+    local jar_name=em-1.0-SNAPSHOT.jar
+    [ -f ${tar_root}/${jar_name} ] || fail "${tar_root}/${jar_name} not found - you need to build the project"
+
+    (cd ${tar_root}; [ -d lib ] || mkdir lib; cp ${jar_name} lib; cp ${M2}/log4j/log4j/1.2.16/log4j-1.2.16.jar lib; tar rf${tar_verbose} ${tar_file} lib) || fail "failed to refresh ${tar_file}"
+
+    gzip ${tar_file}
+
+    [ -f ${gzip_file} ] && debug  "gzip file ${gzip_file} created, size $(ls -l ${gzip_file} | awk '{print $5}') bytes" || fail "failure to create ${gzip_file}"
 
     #
     # scp em.zip and install it on the target instance
@@ -102,9 +116,15 @@ function main()
 
     nfs_server_ip=172.31.25.44
 
-    local remote_command="cd /tmp; [ ! -d ./em ] && mkdir em; cd em; tar xfz${tar_verbose} ../$(basename ${gzip_file}); cd ..; rm ${gzip_file}; ./em/bin/overlays/${overlay} $(serialize-common-arguments) --instance-name ${name} --nfs-server-ip ${nfs_server_ip}"
+    [ -n "${EC2_URL}" ] && ec2_url_arg="--ec2-url ${EC2_URL}" || debug "EC2_URL not found in environment. This means overlay ec2-api-tools will not work correctly on remote instances."
+    [ -n "${AWS_SECRET_KEY}" ] && aws_secret_key_arg="--aws-secret-key ${AWS_SECRET_KEY}" || debug "AWS_SECRET_KEY not found in environment. This means overlay ec2-api-tools will not work on remote instances."
+    [ -n "${AWS_ACCESS_KEY}" ] && aws_access_key_arg="--aws-access-key ${AWS_ACCESS_KEY}" || debug "AWS_ACCESS_KEY not found in environment. This means overlay ec2-api-tools will not work on remote instances."
+
+    local remote_command="cd /tmp; [ ! -d ./em ] && mkdir em; cd em; tar xfz${tar_verbose} ../$(basename ${gzip_file}); cd ..; rm ${gzip_file}; export EM_HOME=/tmp/em; ./em/bin/overlays/${overlay} $(serialize-common-arguments) --instance-name ${name} ${aws_access_key_arg} ${aws_secret_key_arg} ${ec2_url_arg} --nfs-server-ip ${nfs_server_ip}"
     local ssh_sudo_wrapper="ssh -i $(get-installation-identity-file) -t ${ssh_url} sudo -n bash -c \"${remote_command}\""
-    debug "ssh_sudo_wrapper: ${ssh_sudo_wrapper}"
+
+    # mask --aws-secret-key, if present
+    debug "ssh_sudo_wrapper: ${ssh_sudo_wrapper/${aws_secret_key_arg}/--aws-secret-key ***}"
 
     ${ssh_sudo_wrapper} || fail "remote ${name} (${ssh_url}) command failed"
 
