merged 'local' em into the main em, status and sync functional

diff --git a/src/main/bash/bin/commands/sync b/src/main/bash/bin/commands/sync
--- a/src/main/bash/bin/commands/sync
+++ b/src/main/bash/bin/commands/sync
@@ -1,10 +1,9 @@
 #!/bin/bash
 
-[ -f $(dirname $0)/../../lib/em.shlib ] && . $(dirname $0)/../../lib/em.shlib || { echo "$(dirname $0)/../../lib/em.shlib not found" 1>&2; exit 1; }
-[ -f $(dirname $0)/../../lib/linux.shlib ] && . $(dirname $0)/../../lib/linux.shlib || { echo "$(dirname $0)/../../lib/linux.shlib not found" 1>&2; exit 1; }
+lib=$(dirname $0)/../../lib/em.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
+lib=$(dirname $0)/lib/$(basename $0).shlib; [ -f ${lib} ] && . ${lib}
+lib=$(dirname $0)/../../lib/linux.shlib ; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
 
-# also load the individual command lib file if available
-[ -f $(dirname $0)/lib/$(basename $0).shlib ] && . $(dirname $0)/lib/$(basename $0).shlib
 
 function usage()
 {
@@ -37,9 +36,9 @@ function main()
     for i in ${running_instances_name_and_public_ip}; do
         local name=${i%%:*}
         local ip=${i##*:}
-        info "${name} ${ip}"
-        #update-etc-hosts ${name} ${ip}
-        #make_login_links "${name_and_public_ip_for_running_instances}"
+        debug "running instance: ${name}/${ip}"
+        update-etc-hosts ${name} ${ip} && info "${name} address has been updated in /etc/hosts" || debug "/etc/hosts not updated"
+        make-login-shortcut-link $(config LOGIN_SHORTCUT_LINK_DIR) ${name} && info "shortcut link ${name} created" || debug "no shortcut link created"
     done
 }
 
diff --git a/src/main/bash/bin/em b/src/main/bash/bin/em
--- a/src/main/bash/bin/em
+++ b/src/main/bash/bin/em
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-[ -f $(dirname $0)/../lib/em.shlib ] && . $(dirname $0)/../lib/em.shlib || { echo "$(dirname $0)/../lib/em.shlib not found" 1>&2; exit 1; }
+lib=$(dirname $0)/../lib/em.shlib; [ -f ${lib} ] && . ${lib} || { echo "${lib} not found" 1>&2; exit 1; }
 
 export version=1.0
 export release_date="05/06/15"
@@ -21,11 +21,19 @@ EOF
 exit 0
 }
 
+function read-configuration()
+{
+    local conf_file=$(dirname $0)/../etc/em.conf
+    [ -f ${conf_file} ] && . ${conf_file}
+}
+
 function main()
 {
     process-common-arguments $@
 
     [ "${args}" = "" ] && usage;
+
+    read-configuration
 
     #
     # the first "non-common" argument is the command
